#Требования к основному функционалу платформы
functional:
  - Есть возможность создания игры любого уровня сложности
  - Есть возможность выбрать определенный тип игры
  - Если тип игры не выбран, он будет выбран случайно
  - Есть возможность создания игры с ботом или человеком
  - Созданная игра доступна по ссылке
  - Во время игры есть возможность поменять язык програмирования на любой доступный
  - Во время игры участники видят редактор с кодом 
  - Задачи выданы на русском и английском языке
  - Другие пользователи могут подключиться к игре
  - Другие пользователи могут следить за ходом игры
  - Завершенная игра доступна в записи 
  - Доступна отправка инвайта в игру пользователю в сети
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть адоптирован под мобильные устройства
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт отображает количество пользователей онлайн #Нефункциональное требование?
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей) #Пока нет понимания, как его проводить
implicit:
  - При принятии инвайта на игру, пользователя автоматически редиректит в лобби игры

#Требования к функционалу чата
functional:
  - В игре доступен чат для зарегистрированных пользователей
  - Доступна отправка личного сообщения пользователю в сети
  - Доступны смайлы для отправки
  - Отправка сообщения доступна по кнопке
  - Отправка сообщения доступна по клавише "Enter"
non-functional:
  - Защита от XSS в общем чате
  - Защита от XSS в личных сообщениях
implicit:
  - no-data

#Требования к функционалу логина и регистрации
functional:
  - Доступна регистрация по GitHub
  - Доступна регистрация по Discord
  - Имя пользователя должно иметь от 3 до 16 символов
  - Имя пользователя поддерживает латинские символы
  - Имя пользователя должно начинаться с Латинской буквы
  - Имя пользователя может содержать цифры
  - Имя пользователя может содержать "_"
  - Имя пользователя может содержать только одно "-"
  - Поле Email проверяет корректность емейла
  - Учетная запись должна иметь подтверждение емейла #Нужно ли, учтонить?
  - Пароль должен иметь от 6 до 16 символов
  - Поле подтверждения пароля должно совпадать с полем пароля
  - Все поля ввода обязательны
  - На странице логина доступно восстановление пароля
non-functional:
  - no-data
implicit:
  - no-data 

#Требования к cтранице профиля
functional:
  - Доступна привязка Discord к прфоилю аккаунта
  - Доступна привязка GitHub к прфоилю аккаунта
  - Запрещена привязка одного Discord к 2 и более аккаунтам
  - Запрещена привязка одного GitHub к 2 и более аккаунтам
  - Доступна отвязка Discord
  - Доступна отвязка GitHub
non-functional:
  - no-data  
implicit:
  - no-data 

#Требования к блоку рейтинга игроков
functional:
  - Доступна сортировка рейтинга игроков по кнопке "WEEK"
  - Доступна сортировка рейтинга игроков по кнопке "MONTH"
  - Доступна сортировка рейтинга игроков по кнопке "ALL" 
  - Работает переход на страницу users по нажатию "top list"
non-functional:
  - no-data
implicit:
  - no-data

#Требования к странице users
functional:
  - Доступен поиск игроков по никнейму
  - Поиск фильтрует пользователей в реальном времени по совпадаению 
  - Есть сортировка рейтинга по "weekly"
  - Есть сортировка рейтинга по "monthly"
  - Есть сортировка рейтинга по "total"
  - Доступна сортировка с играми против ботов
  - Есть возможность вывода количества юзеров на странице
  - Можно перейти на GitHub аккаунта юзера
  - Доступен переход в профиль юзера на CodeBattle
  - Доступна сортировка по Рангу
  - Доступна сортировка по Рейтингу
  - Доступна сортировка по Сыгранным играм
  - Доступна сортировка по "Joined" #Разобратсья почему сортировка не отображает новых пользователей и свой акк
  - Есть переход на следующую страницу
  - Есть переход на последнюю страницу
  - Можно выбрать страницу рейтинга в диапазоне 5 страниц
non-functional:
  - Список должен содержать информацию о каждом пользователе место, никнейм, ранг, рейтинг, сыгранных матчей, когда присоединился и его гитхаб
  - Выведено значение присоединившихся пользователей
  - Рядом с никнеймом показывается онлайн пользователя
implicit:
  - no-data