#Требования к основному функционалу платформы
functional:
  - Есть возможность создания игры любого уровня сложности
  - Есть возможность выбрать определенный тип игры, 
  - Если тип игры не выбран, он будет выбран случайно
  - Есть возможность создания игры с ботом или человеком
  - Созданная игра доступна по ссылке
  - Во время игры есть возможность поменять язык програмирования на любой доступный
  - Во время игры участники видят редактор с кодом 
  - Задачи выданы на русском и английском языке
  - Другие пользователи могут подключиться к игре
  - Другие пользователи могут следить за ходом игры
  - Завершенная игра доступна в записи 
  - Доступна отправка инвайта в игру пользователю в сети
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть адоптирован под мобильные устройства
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей) # Уточнить про количество и загуглить, как сделать нагрузочное тестировани
  - Сайт отображает количество пользователей онлайн
implicit:
  - При принятии инвайта на игру, пользователя автоматически редиректит в лобби игры


#Требования к функционалу чата
functional:
  - В игре доступен чат для зарегистрированных пользователей
  - Доступна отправка личного сообщения пользователю в сети
  - Доступны смайлы для отправки
non-functional:
  - 
implicit:
  - 

#Требования к функционалу логина и регистрации
functional:
  -
non-functional:
  - 
implicit:
  - 

#Требования к cтранице профиля
functional:
  -
non-functional:
  - 
implicit:
  - 

#Требования к блоку рейтинга игроков
functional:
  -
non-functional:
  - 
implicit:
  - 